collections:
  autores:
    output: true

title: Portfolio
locale: pt_BR
url: https://felpsfon.github.io
baseurl: /Portfolio

defaults:
  - scope:
      path: ""
      type: "autores"
    values:
      layout: "autor"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - github-pages
