collections:
  autores:
    output: true

url: https://felpsfon.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /Portfolio # the subpath of your site, e.g. /blog

defaults:
  - scope:
      path: ""
      type: "autores"
    values:
      layout: "autor"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
